### ISSUE TITLE
potential issues

### ISSUE THREAD

**Issue by mathieucarbou** [hoeken/PsychicHttp#114]
I just run into this part of the code here:

https://github.com/hoeken/PsychicHttp/blob/f769281bce6d375b7cc8246f848dd075053d1ee4/src/PsychicFileResponse.cpp#L106-L109

- buffer can be null if malloc fails
- readSize unused (causes a compiler warning)
- readSize may better be a `size_t`
- readSize probably has to be used in the following line I guess (what if the content length is set with a wrong value)
- size probably has to be set based on the File size ?

**Comment by hitecSmartHome** [comment]
Yeah, there are a lot of missing null pointer checks and yes the content length should use the read size instead.
