### ISSUE TITLE
removeEndpoint(PsychicEndpoint* endpoint);

### ISSUE THREAD

**Issue by hoeken** [hoeken/PsychicHttp#155]
void removeEndpoint(PsychicEndpoint* endpoint); : I didn't have time to spawn it back and the code changed a lot since

**Comment by hoeken** [comment]
@mathieucarbou i think this is finished.  i don't have any code that uses it, so please test and let me know.

**Comment by mathieucarbou** [comment]
> @mathieucarbou i think this is finished. i don't have any code that uses it, so please test and let me know.

I have plenty of use cases in several projects so I will test during migration ;-)
