### ISSUE TITLE
Trouble with params inside uri

### ISSUE THREAD

**Issue by zekageri** [hoeken/PsychicHttp#16]
So i added my own handlers for the server

```cpp
/* strange that i have to add both */
server.on("/db/*", HTTP_GET, &dbHandler);
server.on("/db/*", HTTP_POST, &dbHandler);
```

```cpp
#include <Arduino.h>
#include <PsychicHttp.h>
#include <FileSystem/FileSystem.h>

class DBHandler : public PsychicWebHandler{
    private:
        esp_err_t handleRequest(PsychicRequest *request) override;
        esp_err_t handleDownload(PsychicRequest *request);
};

inline DBHandler dbHandler;
```

```cpp
esp_err_t DBHandler::handleRequest(PsychicRequest *request){
    Serial.printf("[DBHandler] - %s Method: %s\n",request->uri().c_str(),request->methodStr().c_str());
    if( request->url() == "/db/download" ){
        return handleDownload(request);
    }
    return 0;
}
```

When my URL is like for example: `/db/download?path=/hwConfig.json`
This line ` if( request->url() == "/db/download" ) ` will never match. How can i separate the uri and the params? Should i create my own function for this and discard anything after the question mark in the string?

**Comment by zekageri** [comment]
So i have created a method for this

```cpp

void getPath(String url, String &path){
    int index = url.indexOf("?");
    if( index == -1 ){ path = url; return; }
    path = url.substring(0,index);
}

esp_err_t DBHandler::handleRequest(PsychicRequest *request){
    String path;
    getPath(request->url(),path);
    Serial.printf("[DBHandler] - %s Method: %s\n",path,request->methodStr().c_str());
    if( path == "/db/download" ){
        return handleDownload(request);
    }
    return OK;
}
```

Do you think it can be integrated to the server and check it with `request->path()`  which would contain only the path without the params?

**Comment by hoeken** [comment]
If you extend the WebRequest class and override the handleRequest function, you are skipping over all the code that does the body loading, parameter extraction, etc.

The easiest way would be to use the onRequest() method to set a callback and then it will work as intended.

I can see where we could make some improvements here though.  If you have a bunch of variables in your derived class then I'm not sure how you would get that into the callback.  I could modify the base class to have a doRequestCallback() method you could override and then everything would be in the right context.

**Comment by hoeken** [comment]
Actually!  I need to make a change to make the onRequest callback optional, but once I do that, then you can simply call the parent method in your handleRequest and it should all work.  Give me a little bit and I'll push the change

```cpp
esp_err_t DBHandler::handleRequest(PsychicRequest *request){
  PsychicWebHandler::handleRequest(request);
  //your stuff
}

**Comment by hoeken** [comment]
Yes we can add this.

You could also use path.startsWith("/db/download")

**Comment by zekageri** [comment]
Really nice. I will continue the integration tomorrow. I really like it so far.

**Comment by hoeken** [comment]
@zekageri okay i just pushed a commit that adds the request->path() call.
