### ISSUE TITLE
we need a version test macro for client code to follow API changes

### ISSUE THREAD

**Issue by mhaberler** [hoeken/PsychicHttp#160]
[similar to this](https://github.com/hoeken/PsychicHttp/blob/master/src/PsychicHttpsServer.cpp#L31):

`#if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(5, 0, 2)`

**Comment by mhaberler** [comment]
duh, it's in [v2-dev](https://github.com/hoeken/PsychicHttp/blob/v2-dev/src/PsychicVersion.h#L17-L36)

**Comment by hoeken** [comment]
Yeah it's new for v2.  You can use an #ifdef to check v1 to v2
