### ISSUE TITLE
Stuck loading async files

### ISSUE THREAD

**Issue by johnnytolengo** [hoeken/PsychicHttp#184]
Hi, 
I have running a web server (esp32, Psychihttp verison 1.2.1, Using latest Chrome) on static files (js chunk), and sometimes it stuck when loading 
when it happens those request are forever in "Pending". 
After I refresh the browser all loads ok, because  the already loaded are cached in the browser and the missing are loaded again.
Any idea how to fix that?

![image](https://github.com/user-attachments/assets/ca2984b0-980d-4805-be69-6eeabc448b09)

**Comment by hitecSmartHome** [comment]
Increase max open tcp socket in the server config struct

**Comment by johnnytolengo** [comment]
config.max_open_sockets=10;
Fixed that issue.
Thank you!

**Comment by johnnytolengo** [comment]
![image](https://github.com/user-attachments/assets/b8bf77b0-0dfc-4fce-83b6-9b17b7ceeb42)

**Comment by hitecSmartHome** [comment]
Np. You have to read a little bit in the IDF docs and on the internet so you can understand more about it. You will face other challenges down the road as your frontend develops.

**Comment by hitecSmartHome** [comment]
@johnnytolengo  `lru_purge_enable` and `enable_so_linger` options are also useful.
Please close this issue if it is resolved.
