### ISSUE TITLE
Something is wrong with setCacheControl

### ISSUE THREAD

**Issue by zekageri** [hoeken/PsychicHttp#24]
Something was very sus from the start when i started to use this lib.
I use setCacheControl to every request.

```cpp
#define MAX_CACHE_CONTROL_TIME "max-age=31536000"
#define ONE_DAY_CACHE_TIME "max-age=86400"
#define ONE_HOUR_CACHE_TIME "max-age=3600"
#define SEVEN_DAY_CACHE_TIME "max-age=172800"

server.serveStatic("/", db.sysFS, "/")->setCacheControl(ONE_HOUR_CACHE_TIME);
```

It properly caches my files but when that one hour is up i have to clear my caches in the browser because nothing is loading.
It was not a problem with Async webserver. I will investigate it further but it is really strange.

In the network tab i see the following after one hour

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/942190d5-3958-4da3-9516-b0e367897feb)
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/0ca744ab-849a-42ee-afc5-5cd8d12eefed)
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/52be74d9-69b1-424f-b16c-dd8fc8f87fff)

**After i deleted cache**

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/1d52bf61-bf0c-4e69-830a-24e68eee2ea2)
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/a5fdb6e1-eb57-49c2-9399-fb51593bfb40)

**After i refreshed with cached contents ( and working )**

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/57ddae5e-7dce-4034-ad25-c65d853f60de)
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/f5135ef7-3843-4179-90ab-5dace3b04836)

**Comment by zekageri** [comment]
**Here are the response headers after one hour before cache delete**

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/d509ef70-45ac-47fd-8f59-a6da10ed0316)

**And after one hour after cache delete**

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/c3204333-ee12-4406-9ed3-b61cb45f5ac5)

**Comment by hoeken** [comment]
Just pushed a potential fix.  Looks like there was a missing call to set the response code to 304 when checking the etags

**Comment by zekageri** [comment]
Yeah, it keeps logging these

PsychicStaticFileHander.cpp:144: _filename = /Manifest/favicon.ico
PsychicStaticFileHander.cpp:173: "No cache hit" = No cache hit
PsychicStaticFileHander.cpp:174: _last_modified =
PsychicStaticFileHander.cpp:175: _cache_control = max-age=3600
PsychicStaticFileHander.cpp:144: _filename = /Pages/HomePage/quickLights.css
PsychicStaticFileHander.cpp:173: "No cache hit" = No cache hit
PsychicStaticFileHander.cpp:174: _last_modified =
PsychicStaticFileHander.cpp:175: _cache_control = max-age=3600
PsychicStaticFileHander.cpp:144: _filename = /947.js
PsychicStaticFileHander.cpp:173: "No cache hit" = No cache hit
PsychicStaticFileHander.cpp:174: _last_modified =
PsychicStaticFileHander.cpp:175: _cache_control = max-age=3600

**Comment by hoeken** [comment]
Ah sorry I forgot to mention I left those in there to help tracking down
the bug if that doesn't fix it.

Let me know if it's fixed and I'll remove them.

**Comment by zekageri** [comment]
Testing

**Comment by zekageri** [comment]
It seems to work. I have tested it on

**Android**
- Chrome
- Firefox

**Windows**
- Edge
- Chrome
- Brave
