### ISSUE TITLE
OTA Update

### ISSUE THREAD

**Issue by bbasil2012** [hoeken/PsychicHttp#30]
Whats about OTA ?

**Comment by hoeken** [comment]
Its definitely possible.  There are many ways to do it.  Anything in particular?

**Comment by bbasil2012** [comment]
Yes. My firmware file size exceeds 200K
I'm getting a message can't upload a file larger than 200K

**Comment by hoeken** [comment]
Ah, yeah that's a configurable setting:

```cpp
server.maxUploadSize = bytes
```

**Comment by bbasil2012** [comment]
Ok, I will try )
Very great lib!!!

**Comment by bbasil2012** [comment]
It's worked !!! (c)
Here is my example code:

const uint32_t maxSketchSpace = 0x140000;
server.maxUploadSize=maxSketchSpace;
server.on("/update", HTTP_POST)->onUpload(updateHandler);

esp_err_t updateHandler(PsychicHttpServerRequest *request, const String& filename, uint64_t index, uint8_t *data, size_t len)
{
  if(!index){
    Serial.println("Begin OTA update");
    if(!Update.begin(maxSketchSpace)){
        Update.printError(Serial);
    }
  }
  if(!Update.hasError()){
      Serial.print(".");
      if(Update.write(data, len) != len){
        Update.printError(Serial);
      }
  }
  if (len<FILE_CHUNK_SIZE){
     if(Update.end(true)){
        Serial.printf("\nUpdate Success in: %u Bytes\n", index+len);
        ESP.restart();
      } else {
        Update.printError(Serial);
      }
  }
  return ESP_OK;
}

And example with curl:
curl -X POST -k -T firmware.bin https://<ip address or fqdn>/update

**Comment by bbasil2012** [comment]
Done

**Comment by Mr-HaleYa** [comment]
Great job!

Close the issue if you have solved your question
