### ISSUE TITLE
URIs added before listen() not working

### ISSUE THREAD

**Issue by proddy** [hoeken/PsychicHttp#34]
quesiton: I'm registering some of my endoints with server.on() before the listener and WiFi are started, and they are being ignored. There are no errors and I can't trace why.

Do you know if httpd_start() needs to executed first before httpd_register_uri_handler() ?

**Comment by zekageri** [comment]
Yes. Listen should be the first

**Comment by proddy** [comment]
and if I may add, starting the HTTP listener before the network (wifi, eth) is enabled will crash the ESP32

**Comment by hoeken** [comment]
@proddy interesting.  its probably worth adding a check to the listen() call then.
