### ISSUE TITLE
starting the HTTP listener before the network (wifi, eth) is enabled will crash the ESP32

### ISSUE THREAD

**Issue by hoeken** [hoeken/PsychicHttp#35]
reported by @proddy

**Comment by Chris--A** [comment]
I'm just starting out testing which server framework to use (PsychicHTTP is the winner so far), so I haven't had a chance to test this yet; however, in case it is already known, would this issue also affect the circumstances when wifi is disconnected to change connections?

**Comment by proddy** [comment]
it should be fine, as long as the `WiFi.mode()` has been called once before `server.listen()`. This is because WiFi.mode calls IDF's `esp_wifi_start()`. Any `WiFi.begin()`'s or reconnect code can safely happen afterwards.

**Comment by hoeken** [comment]
Fixed
