### ISSUE TITLE
request->body() is incomplete?

### ISSUE THREAD

**Issue by zekageri** [hoeken/PsychicHttp#48]
I have a handler which looks like this:

```cpp
esp_err_t HardwareHandler::saveHardware(PsychicRequest *request) {
    DynamicJsonDocument doc(request->contentLength() * 3);
    DeserializationError error = deserializeJson(doc, request->body()); // Code fails to deserialize. InvalidInput
    if (error) {
        Serial.println(request->body());
        return request->reply(500,"text/plain",error.c_str());
    }
    boolean status = hwConfig.updateModule(doc);
    return request->reply(status ? 200 : 400);
}
```

I can't deserialize the incoming json because it is incomplete.
I adjusted the `MAX_REQUEST_BODY_SIZE` to `(30*1024)` in `PsychicCore.h` but no success.

The handler is called like this

```cpp
esp_err_t HardwareHandler::handleRequest(PsychicRequest *request) {
    request->loadBody();
    request->loadParams();
    if (request->path() == "/hardwares/save" && request->method() == HTTP_POST) {
        return saveHardware(request);
    }
    return ESP_OK;
}
```

If i print the body raw i get garbage at the end. The request should fit into 10k at max.
I also have plenty of RAM left.
Here are the headers

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/53d7edf7-46d3-434e-bf9d-93b615eb912e)

Some garbage data from the print of the raw request body

```cpp
���{"moduleAddress":13,"name":"b���OUT 29","displayName":"R32-Oz���9","type":0,"current":0,"faur���de":0,"relayCount":206,"regNJ���r":1,"pinNumber":12,"readablB���Number":29,"state":false,"vaZ���:0,"id":"R32_CF4F6760"},"R32R���42A8B":{"moduleAddress":13,"����":"R32-OUT 30","displayName"����2-OUT 30","type":0,"current"����faultCode":0,"relayCount":15����egNumber":1,"pinNumber":13,"����ablePinNumber":30,"state":fa����"value":0,"id":"R32_8F842A8B����R32_745132C1":{"moduleAddres����3,"name":"R32-OUT 31","displ궪�me":"R32-OUT 31","type":0,"cⶪ�nt":0,"faultCode":0,"relayCo����:100,"regNumber":1,"pinNumbe򶪪4,"readablePinNumber":31,"s tʶ��:false,"value":0,"id":"R32_7¶��2C1"},"R32_6CD83A42":{"modulڶ��ress":13,"name":"R32-OUT 32"Ҷ��splayName":"R32-OUT 32","typ*���,"current":0,"faultCode":0,""���yCount":22022,"regNumber":1,:���Number":15,"readablePinNumbe2���2,"state":false,"value":0,"i
���R32_6CD83A42"}}}
```

**Comment by zekageri** [comment]
Here is the ArduinoJson assistant output for the object

![image](https://github.com/hoeken/PsychicHttp/assets/37899881/1d02af29-cd94-4965-b7db-155914f6b3fc)

**Comment by zekageri** [comment]
Some strange thing is happening. Doesn't matter if i increase the `MAX_REQUEST_BODY_SIZE` to even `(100*1024)` the request body is incomplete. What is going on?

**Comment by proddy** [comment]
just quick thoughts here
- are you sure you're using the PsychicJsonRequestCallback - otherwise the json payload on the POST won't be identified, then you only need to send the jsonobject in your saveHardware()
- I'm having a lot of fun with PR #45 and chunk streaming. See an example at https://github.com/hoeken/PsychicHttp/issues/37#issuecomment-1874075859

**Comment by zekageri** [comment]
I don't use it, it was not available before.
I have a custom class made to handle specific requests like this one

```cpp
server.on("/hardwares/*", HTTP_GET, &hardwareHandler);
server.on("/hardwares/*", HTTP_POST, &hardwareHandler);

esp_err_t HardwareHandler::handleRequest(PsychicRequest *request) {
    request->loadBody();
    request->loadParams();
    if (request->path() == "/hardwares/scann") {
        return scann(request);
    } else if (request->path() == "/hardwares/save" && request->method() == HTTP_POST) {
        return saveHardware(request);
    }
   // More handlers...
    return ESP_OK;
}

esp_err_t HardwareHandler::saveHardware(PsychicRequest *request) {
    DynamicJsonDocument doc(request->contentLength() * 2);
    DeserializationError error = deserializeJson(doc, request->body());
    if (error) {
        Serial.println(request->body());
        return request->reply(500,"text/plain",error.c_str());
    }
    int status = hwConfig.updateModule(doc) ? 200 : 400;
    return request->reply(status);
}
```

**Comment by zekageri** [comment]
Thanks for the example but I don't send json in this handler, i send 200 or 400 or 500, i want to accept it.

**Comment by zekageri** [comment]
I will try it like this and see what happens

```cpp
server.on("/hardwares/save", HTTP_POST, [](PsychicRequest *request){
    return hardwareHandler.saveHardware(request);
});
```

**Comment by zekageri** [comment]
Same, `InvalidInput` error message from ArduinoJson...

**Comment by zekageri** [comment]
Will check it like this

```cpp
server.on("/hardwares/save", HTTP_POST, [](PsychicRequest *request,JsonVariant &json){
    //return hardwareHandler.saveHardware(request);
    serializeJson(json, Serial);
    return ESP_OK;
});
```

**Comment by zekageri** [comment]
Well, it prints nothing.

**Comment by proddy** [comment]
if you convert the jsonvariant into a doc?

```
    if (!json.is<JsonObject>()) {
            StaticJsonDocument<1024> input_doc;
            JsonObject                                 input = input_doc.to<JsonObject>();
            serializeJson(input, Serial);
            return hardwareHandler.saveHardware(request, input);
        }
```

ArduinoJson 7 which is just out makes this easier, but above is the old way

**Comment by Chris--A** [comment]
I started with V7, however, I found that I was getting some extra heap fragmentation from a small amount of use. I switched back to V6 so I could use static buffers. I might change things soon, ordered 2x new ESP32-S3 with 16MB flash and 8MB PSRAM, so I can be a bit more flexible.

**Comment by zekageri** [comment]
> if you convert the jsonvariant into a doc?
> 
> ```
>     if (!json.is<JsonObject>()) {
>             StaticJsonDocument<1024> input_doc;
>             JsonObject                                 input = input_doc.to<JsonObject>();
>             serializeJson(input, Serial);
>             return hardwareHandler.saveHardware(request, input);
>         }
> ```
> 
> ArduinoJson 7 which is just out makes this easier, but above is the old way

Will Check!

**Comment by zekageri** [comment]
> I started with V7, however, I found that I was getting some extra heap fragmentation from a small amount of use. I switched back to V6 so I could use static buffers. I might change things soon, ordered 2x new ESP32-S3 with 16MB flash and 8MB PSRAM, so I can be a bit more flexible.

Wow, thats not what we are used to from ArduinoJson

**Comment by Chris--A** [comment]
> Wow, thats not what we are used to from ArduinoJson

I'll have to do more testing, likely a me issue, but I do also prefer stack allocations where I can which is a V6 feature.

**Comment by proddy** [comment]
> > Wow, thats not what we are used to from ArduinoJson
> 
> I'll have to do more testing, likely a me issue, but I do also prefer stack allocations where I can which is a V6 feature.

same here, I use StaticJsonDocument for anything less than 1024 bytes, because of fragmentation (and max alloc buffer size).

**Comment by zekageri** [comment]
With this line

server.on("/hardwares/save", HTTP_POST, [this](PsychicRequest *request, JsonVariant &json){});

The server just throws a 400 bad request to the client and i can't see anyting now.

**Comment by zekageri** [comment]
I'm pulling my hair out

**Comment by zekageri** [comment]
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/7ec86f3c-57be-4415-a677-b1c29f56d83a)
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/bf8b9519-5f1c-484f-aaf0-9dbaa9b4adcf)

**Comment by zekageri** [comment]
This is my handler now but does not print anything. My handler doesn't even called.

```cpp
server.on("/hardwares/save", HTTP_POST, [this](PsychicRequest *request, JsonVariant &json){
    Serial.print("RAW BODY: ");
    Serial.println(request->body());
    Serial.print("Json Variant: ");
    serializeJson(json, Serial);
    if (!json.is<JsonObject>()) {
        StaticJsonDocument<1024> input_doc;
        JsonObject input = input_doc.to<JsonObject>();
        Serial.println("Input Object: ");
        serializeJson(input, Serial);
    }
    return request->reply(500);
});
```

**Comment by proddy** [comment]
also add `-D ARDUINOTRACE_ENABLE=1` as there are some extra debugging in the lib which could help you

**Comment by proddy** [comment]
and if you're getting 400, it's probably because the json is incorrectly formatting. Look at the code in PsychicWebHandler::handleRequest() and add some more debugging lines to show the error code from ArduinoJson

**Comment by zekageri** [comment]
Will try this thank!

**Comment by zekageri** [comment]
It writes nothing to the Serial. O_o

**Comment by zekageri** [comment]
handleRequest has some debugging already but it prints nothing

```cpp
esp_err_t PsychicWebHandler::handleRequest(PsychicRequest *request)
{
  //lookup our client
  PsychicClient *client = checkForNewClient(request->client());
  if (client->isNew)
    openCallback(client);

  /* Request body cannot be larger than a limit */
  if (request->contentLength() > request->server()->maxRequestBodySize)
  {
    ESP_LOGE(PH_TAG, "Request body too large : %d bytes", request->contentLength());

    /* Respond with 400 Bad Request */
    char error[60];
    sprintf(error, "Request body must be less than %u bytes!", request->server()->maxRequestBodySize);
    httpd_resp_send_err(request->request(), HTTPD_400_BAD_REQUEST, error);

    /* Return failure to close underlying connection else the incoming file content will keep the socket busy */
    return ESP_FAIL;
  }

  //get our body loaded up.
  esp_err_t err = request->loadBody();
  if (err != ESP_OK)
    return err;

  //load our params in.
  request->loadParams();

  //okay, pass on to our callback.
  if (this->_requestCallback != NULL)
    err = this->_requestCallback(request);

  return err;
}
```

**Comment by zekageri** [comment]
Sometimes i just get 400 bad request but sometimes it does do something.
Sometimes my cb gets called and passes an incomplete body

**Here is the result ( trimmed down the raw body print )**

```cpp
RAW BODY: "R32_C2B889A2":{"moduleAddress":13,"name":"R32-OUT 10","displayName":"R32-OUT 10","type":0,"current":0,"faultCode":0,"relayCount":247,<b�?
Json Variant: "M8_083A02B2"
Input Object:
{}
```

This is the handler

```cpp
server.on("/hardwares/save", HTTP_POST, [this](PsychicRequest *request, JsonVariant &json){
    Serial.print("RAW BODY: ");
    Serial.println(request->body());
    Serial.print("Json Variant: ");
    serializeJson(json, Serial);
    if (!json.is<JsonObject>()) {
        StaticJsonDocument<1024> input_doc;
        JsonObject input = input_doc.to<JsonObject>();
        Serial.println("\nInput Object: ");
        serializeJson(input, Serial);
    }
    return request->reply(500);
});
```

**Comment by proddy** [comment]
I just tried your code above, in the standard test and it works. it prints out the json. Only the Input Object not because of the !json is incorrect

**Comment by hoeken** [comment]
@zekageri it looks like the json you're sending might be bad or have non-ascii characters.  To debug where that is happening, can you have your sending code print that json, save it to a file.  Verify it with an online json parser, and then once you know its good, use curl to emulate the request.  If its still malformed its an issue in PsychicHttp.

```
curl -i -X POST -H "Content-Type: application/json" --data-binary "@/path/to/filename" http://psychic.local/api
```

**Comment by zekageri** [comment]
Json is produced by a javascript client and stringified when sending. The transfer is happening with standard javascript fetch request. I have printed the object in the console on client side and i also verified it with ArduinoJson assistant. The dev console also confirms it is good.

**Comment by hoeken** [comment]
Can you try the curl command and post the results?

**Comment by zekageri** [comment]
Yap i will in a couple of hours. Btw this object and the front end code is not modified after i transitioned to psychic from asynctcp. And it worked before.

**Comment by zekageri** [comment]
```curl
curl -i -X POST -H "Content-Type: application/json" --data-binary "@D:\test.json" http://hsh.local/upload/?path=/tempModule.json&partition=user
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 15
Server: HsH Server

Upload success!'partition' is not recognized as an internal or external command,
operable program or batch file.
```

Seems to me that curl doesn't know how to handle params? :D

**Comment by zekageri** [comment]
Strange thing is that i have switched to upload handling instead of normal web request handler ( i tought that the size was the problem ) but the result is the same. It is trully looks like that my object is malformed but it is not. I attach the json object as a file here.

This is the object what is causing the issue.
[test.json](https://github.com/hoeken/PsychicHttp/files/13827213/test.json)

**Comment by zekageri** [comment]
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/34a10c33-7a0c-4f0e-8c8c-7b8c0e67b44e)

**Comment by zekageri** [comment]
Will try a curl on a regular json endpoint in a minute

```cpp
server.on("/hardwares/newSave", HTTP_POST, [this](PsychicRequest *request, JsonVariant &json){
    serializeJsonPretty(json, Serial);
    return request->reply(200);
});
```

**Comment by zekageri** [comment]
Same file with this endpoint

**ESP Serial:**
`"state"`
**Curl**
```
curl -i -X POST -H "Content-Type: application/json" --data-binary "@D:\test.json" http://hsh.local/hardwares/newSave
HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 2
Server: HsH Server

OK
```

**Comment by zekageri** [comment]
Maybe this is the problem in the lib

#if ARDUINOJSON_VERSION_MAJOR == 5
  #define ARDUINOJSON_5_COMPATIBILITY
#else
  #ifndef DYNAMIC_JSON_DOCUMENT_SIZE
    #define DYNAMIC_JSON_DOCUMENT_SIZE 4096
  #endif
#endif

#ifndef JSON_BUFFER_SIZE
  #define JSON_BUFFER_SIZE 4*1024
#endif

**Comment by zekageri** [comment]
No, it wasnt. :(

**Comment by zekageri** [comment]
Why is it jsonVariant? Why not JsonDocument in the cb?

**Comment by zekageri** [comment]
If i print the raw `request->body()` it is also malformed in the `esp_err_t PsychicJsonHandler::handleRequest(PsychicRequest *request)`

```cpp
esp_err_t PsychicJsonHandler::handleRequest(PsychicRequest *request)
{
  //process basic stuff
  PsychicWebHandler::handleRequest(request);

  if (_onRequest)
  {
    #ifdef ARDUINOJSON_5_COMPATIBILITY
      DynamicJsonBuffer jsonBuffer;
      JsonVariant json = jsonBuffer.parse();
      if (!json.success())
        return request->reply(400);
    #else
      DynamicJsonDocument jsonBuffer(this->_maxJsonBufferSize);
      DeserializationError error = deserializeJson(jsonBuffer, request->body());
      if (error)
        return request->reply(400);

      Serial.println(request->body());
      Serial.println();
      serializeJsonPretty(jsonBuffer, Serial);
      JsonVariant json = jsonBuffer.as<JsonVariant>();
    #endif

    return _onRequest(request, json);
  }
  else
    return request->reply(500);
}
```

The start of the object is missing and the end of it.

**Comment by zekageri** [comment]
Since String uses malloc() and i have set malloc to allocate from my ext ram, i really doubt that it would be insufficient memory. But i will check my free ram too.

**Comment by zekageri** [comment]
As you can see i have `136640 byte` heap free and `3118471 byte` ext ram free before the curl request.
And almost the same after.

```cpp
[SYSTEM] - [HEAP][1]
Free:   136640
Min:    136640
Max:    136640
Contig: 90100
Diff:   32


[SYSTEM] - [EXT][1]
Free:   3118471
Min:    3118471
Max:    3118471
Contig: 3014644
Diff:   1552

[Server] - Connection #54 connected from 192.168.10.114
"name""name"

[SYSTEM] - [HEAP][1]
Free:   136672
Min:    136672
Max:    136672
Contig: 90100
Diff:   32


[SYSTEM] - [EXT][1]
Free:   3120023
Min:    3120023
Max:    3120023
Contig: 3014644
Diff:   1552
```

**Comment by proddy** [comment]
I'd recommend you take the example 'platformio' code,  modify the `main.cpp` with just your code to help isolate the problem. Then we can all 'chip in' and make it work. That's what I did when I ran into memory & performance issues.

**Comment by zekageri** [comment]
Yeah, i have no other choice left. Thanks. WIll try!

**Comment by zekageri** [comment]
So i have copyed the platformio example and added this handler

```cpp
server.on("/testSave", HTTP_POST, [](PsychicRequest *request, JsonVariant &json) {
    // Because it can split out some strings which is valid JSON
    static const int MIN_LENGTH = 20;
    Serial.println();
    int len = serializeJsonPretty(json, Serial);
    Serial.println();
    return request->reply(len>MIN_LENGTH?200:500, "text/plain", len>MIN_LENGTH?"OK":"Failed");
});
```

On the client side i have created a button and a text area field where you can copy a json object or whatever json. When you click a button it makes a request to this endpoint which will print it out. I used my JSON from the file i uploaded here earlier and the result is the same. It just wont deserialize properly.

Here is the test repo: https://github.com/zekageri/Psychic_Upload_Test

**Comment by zekageri** [comment]
On the front end side i do this

```js
const testJsonButton = document.querySelector("#testJsonBtn");
const testJsonField = document.querySelector("#testJson");

testJsonButton.addEventListener('click', async function(){
    if( testJsonField.value.length == 0 ){
        alert("No test json provided");
        return;
    }
    const jsonText = JSON.parse( testJsonField.value );
    const response = await fetch("/testSave",{
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(jsonText)
    });
    alert( response.ok?"Success":"Failed" );
    testJsonField.value = "";
}, false);
```

parsing the value of the textarea because i have an actual object in my tests and we can stringify it again to make it more real case.

**Comment by zekageri** [comment]
I even got a crash now

```cpp
Core  1 register dump:
PC      : 0x4008cf01  PS      : 0x00060430  A0      : 0x8021a37c  A1      : 0x3ffdcdc0
A2      : 0x00000000  A3      : 0xfffffffc  A4      : 0x000000ff  A5      : 0x0000ff00
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3f82ad70
A10     : 0x00000001  A11     : 0x0000007d  A12     : 0x00000000  A13     : 0x00000000
A14     : 0x0000000e  A15     : 0x00060023  SAR     : 0x00000015  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x4008cf01  LEND    : 0x4008cf11  LCOUNT  : 0xffffffff


Backtrace: 0x4008cefe:0x3ffdcdc0 0x4021a379:0x3ffdcdd0 0x40221416:0x3ffdd0e0 0x40221452:0x3ffdd170 0x4011e7b1:0x3ffdd1b0 0x400d888c:0x3ffdd200 0x400d9a11:0x3ffdd330 0x40133ee5:0x3ffdd380 0x40133f21:0x3ffdd3e0 0x4014d4d1:0x3ffdd400 0x4014dda1:0x3ffdd470 0x40198475:0x3ffdd4f0 0x4019726c:0x3ffdd520 0x40197a9a:0x3ffdd5c0 0x4019663c:0x3ffdd5e0 0x40233446:0x3ffdd600 0x40196761:0x3ffdd620

  #0  0x4008cefe:0x3ffdcdc0 in strlen at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32-elf/src/newlib/newlib/libc/machine/xtensa/strlen.S:82




ELF file SHA256: bbf7c306adf71612

Rebooting..
```

**Comment by zekageri** [comment]
Oh the crash was my bad because i passed a badly deserialized json string coming from the handler.

**Comment by hoeken** [comment]
Put the URL in quotes.

**Comment by zekageri** [comment]
Can you elaborate please?

**Comment by proddy** [comment]
'click' to "click"

**Comment by zekageri** [comment]
Am i this dumb or are you just messing with me

**Comment by zekageri** [comment]
Every one of the urls are in quotes. On the frontend side as well as on the endpoints. Even in the curl command. I dont know what you are referring to

**Comment by proddy** [comment]
oh, your example was JS code, then single-quote is ok

**Comment by zekageri** [comment]
So I still don't understand.

**Comment by zekageri** [comment]
The event handler is worked regardless of the type of the code.
It posts the json text fine. The problem was again with the body loading of the library.
It does this even with the platformio test sketch.

**Comment by zekageri** [comment]
- I have enough internal and external ram
- The Json message fits to the default body size
- The body text is malformed even in the `handleRequest` method of the `PsychicWebHandler` class in the lib's code
- I have confirmed with the test sketch that it is not working properly

**Comment by proddy** [comment]
> I started with V7, however, I found that I was getting some extra heap fragmentation from a small amount of use. I switched back to V6 so I could use static buffers. I might change things soon, ordered 2x new ESP32-S3 with 16MB flash and 8MB PSRAM, so I can be a bit more flexible.

FYI I just ported ArduinoJson to V7 and the memory footprint is identical. Which is comforting. Both Available Heap and Max Alloc are the same. It does feel slightly nippier, especially processing MsgPacks, but maybe that's just my brain wanted to see some overall improvement from all the silly hours I spent this week.

**Comment by zekageri** [comment]
I'm porting it to V7 just now too. But that incomplete request body just makes me angryer. That is the only thing holding me back right now.

**Comment by proddy** [comment]
I'll see if I can take a look at your example code today, still in https://github.com/zekageri/Psychic_Upload_Test ?

**Comment by zekageri** [comment]
Yes, thank you very much. Use the file i uploaded here.

**Comment by zekageri** [comment]
> Strange thing is that i have switched to upload handling instead of normal web request handler ( i tought that the size was the problem ) but the result is the same. It is trully looks like that my object is malformed but it is not. I attach the json object as a file here.
> 
> This is the object what is causing the issue. [test.json](https://github.com/hoeken/PsychicHttp/files/13827213/test.json)

This was the comment i uploaded my example json file. Since then i tryed much smaller jsons and they all fail. Really small jsons are okay however

**Comment by zekageri** [comment]
> > I started with V7, however, I found that I was getting some extra heap fragmentation from a small amount of use. I switched back to V6 so I could use static buffers. I might change things soon, ordered 2x new ESP32-S3 with 16MB flash and 8MB PSRAM, so I can be a bit more flexible.
> 
> FYI I just ported ArduinoJson to V7 and the memory footprint is identical. Which is comforting. Both Available Heap and Max Alloc are the same. It does feel slightly nippier, especially processing MsgPacks, but maybe that's just my brain wanted to see some overall improvement from all the silly hours I spent this week. Oh and it's an S3 with 16MB/8 PSRAM too.

Did you changed the Psychic lib too?
I had to do a couple of changes to migrate to ArduinoJson v7

**Comment by zekageri** [comment]
![image](https://github.com/hoeken/PsychicHttp/assets/37899881/e8f54f76-fd1e-4366-b86a-6d124c77097a)

This is just too big. If i remove one object from the json and it will became 5.5kb in size, it works.

**Comment by proddy** [comment]
I would use ArduinoJson 7 then you don't need to worry about sizes and allocating buffers. Also suggest you use MsgPack which can compress your load by 30-40% (unless binary). And lastly stream with chunking using Chris's PR. But first we need to fix the root cause of your initial error.

**Comment by zekageri** [comment]
I migrated to v7 and i also use the PR. It doesn't matter. I changed some stuff in the lib to better support ArduinoJson7 like this function

```cpp
esp_err_t PsychicJsonHandler::handleRequest(PsychicRequest *request)
{
  //process basic stuff
  PsychicWebHandler::handleRequest(request);

  if (_onRequest)
  {
    #ifdef ARDUINOJSON_5_COMPATIBILITY
      DynamicJsonBuffer jsonBuffer;
      JsonVariant json = jsonBuffer.parse();
      if (!json.success())
        return request->reply(400);
    #else
      //DynamicJsonDocument jsonBuffer(this->_maxJsonBufferSize);
      JsonDocument jsonBuffer;
      DeserializationError error = deserializeJson(jsonBuffer, request->body());
      if (error)
        return request->reply(400);

      JsonVariant json = jsonBuffer.as<JsonVariant>();
    #endif

    return _onRequest(request, json);
  }
  else
    return request->reply(500);
} 
```

Result is the same again. I can't belive this. I can't find any restrictions on sizes anymore, i removed and changed the sizes in the lib like this

```cpp
#if ARDUINOJSON_VERSION_MAJOR == 5
  #define ARDUINOJSON_5_COMPATIBILITY
#else
  #ifndef DYNAMIC_JSON_DOCUMENT_SIZE
    #define DYNAMIC_JSON_DOCUMENT_SIZE 4096
  #endif
#endif

#ifndef JSON_BUFFER_SIZE
  #define JSON_BUFFER_SIZE 4*1024
#endif
```

to this

```cpp
#if ARDUINOJSON_VERSION_MAJOR == 5
  #define ARDUINOJSON_5_COMPATIBILITY
#else
  #ifndef DYNAMIC_JSON_DOCUMENT_SIZE
    #define DYNAMIC_JSON_DOCUMENT_SIZE 40096
  #endif
#endif

#ifndef JSON_BUFFER_SIZE
  #define JSON_BUFFER_SIZE 16*1024
#endif
```

I also specify the size in my sketch like this

```cpp
server.maxUploadSize = MAX_UPLOAD_SIZE;
server.maxRequestBodySize = MAX_REQUEST_BODY_SIZE;
```

I can't find any reason anymore.

**Comment by zekageri** [comment]
All of these modifications was made on my big project. But i will update the test repo too.

**Comment by zekageri** [comment]
Updated the test repo to ArduinoJsonV7.
Added these

```cpp
server.maxUploadSize = MAX_UPLOAD_SIZE;
server.maxRequestBodySize = MAX_REQUEST_BODY_SIZE;
```

Modified this method to AJV7

```cpp
esp_err_t PsychicJsonHandler::handleRequest(PsychicRequest *request)
{
  //process basic stuff
  PsychicWebHandler::handleRequest(request);

  if (_onRequest)
  {
    #ifdef ARDUINOJSON_5_COMPATIBILITY
      DynamicJsonBuffer jsonBuffer;
      JsonVariant json = jsonBuffer.parse();
      if (!json.success())
        return request->reply(400);
    #else
      //DynamicJsonDocument jsonBuffer(this->_maxJsonBufferSize);
      JsonDocument jsonBuffer;
      DeserializationError error = deserializeJson(jsonBuffer, request->body());
      if (error)
        return request->reply(400);

      JsonVariant json = jsonBuffer.as<JsonVariant>();
    #endif

    return _onRequest(request, json);
  }
  else
    return request->reply(500);
}
```

Test endpoint still there

```cpp
server.on("/testSave", HTTP_POST, [](PsychicRequest *request, JsonVariant &json) {
    // Because it can split out some strings which is valid JSON
    static const int MIN_LENGTH = 20;
    Serial.println();
    int len = serializeJsonPretty(json, Serial);
    Serial.println();
    return request->reply(len>MIN_LENGTH?200:500, "text/plain", len>MIN_LENGTH?"OK":"Failed");
});
```

**Comment by zekageri** [comment]
I will close this and start a new issue because it's getting too long. I want to pack my test cases into a more compressed question. I hope it will sort out soon because i really have tried everything in my power.

**Comment by zekageri** [comment]
Here is the new issue https://github.com/hoeken/PsychicHttp/issues/58
