### ISSUE TITLE
Serving html file with GET-style parameters in redirect url

### ISSUE THREAD

**Issue by myqel** [hoeken/PsychicHttp#49]
I want to use the separate login page concept with simple cockie handling from here as tutorial 04:
[https://github.com/xreef/WebServer-Esp8266-ESP32-Tutorial](https://github.com/xreef/WebServer-Esp8266-ESP32-Tutorial)
The login page file has an own small javascript function to read parameter in its URL and is called via redirect as "/login.html?msg=_Text here_". The GET style is not intended to be processed by the server.
The WebServer and AsyncWebServer examples of the author above handle the URI with default file serving code which seems cut the parameter part off to get the uri as filename correctly. In my code with PsychicHttp I had to cut the path in the file handling by
`server.onNotFound([](PsychicRequest *request){`
`  String path = request->url();`
`  path = path.substring(0, path.indexOf('?'));` 
`...`
`else if(LittleFS.exists(path)) {`
`        PsychicFileResponse response(request, LittleFS, path, dataType, false);`
`        return response.send();`
`      }`
The redirect works like intended then. The file is found by file download handler and the redirect() hands over to full url to the browser.

`server.serveStatic("/", LittleFS, "/",...` seems to keep the long uri, too, as the request reaches my onNotFound().
(But I do not use the static rule because of authentifcation concept)

Did I miss the correct file request response for this case maybe as it is realized differently with PsychicHttp?

Best regards; Michael

**Comment by hoeken** [comment]
I know this is a super late reply, but:

```request->url()``` is the entire url eg. ```/login?foo=bar```
```request->path()``` is the file path eg. ```/login```
```request->query()``` is the query string eg. ```foo=bar```
```request->getParam('foo')->getValue()``` gets the parameter data, eg. ```bar```
