### ISSUE TITLE
Iphone downloads the gz file instead of rendering it.

### ISSUE THREAD

**Issue by zekageri** [hoeken/PsychicHttp#63]
It happens when i send a file with PsychicFileResponse

```cpp
PsychicFileResponse response(request,LittleFs,INDEX_PATH,"text/html");
response.addHeader("Content-Encoding", "gzip");
response.addHeader("Cache-Control", ONE_MONTH_CACHE_TIME);
return response.send();
```

But it does not happen if it is a static file serve.

**Comment by Chris--A** [comment]
Hey @zekageri,

What is `INDEX_PATH`? 
Is it just something like `index.html`, or `index.html.gz`, or just `index.gz`?

**Comment by zekageri** [comment]
Oh I see. The path was indeed `index.html.gz`. Thank you very much! This makes sense.
