### ISSUE TITLE
Websocket client and server at the same time?

### ISSUE THREAD

**Issue by zekageri** [hoeken/PsychicHttp#66]
Can it be done to create a client and a server websocket at the same time?
I want to connect to a node.js server via websockets and i don't want to use an other library
and i don't want to give up my ws server for local connection.

**Comment by theelims** [comment]
There is a websocket client library in the ESP-IDF. You could try to use that. I see no point why it shouldn't work.

**Comment by zekageri** [comment]
Will check, thanks
