### ISSUE TITLE
Compatibility with esp8266 

### ISSUE THREAD

**Issue by DaeMonSxy** [hoeken/PsychicHttp#67]
Any intenaion/solution to make it work with esp8266 also?
Like ESPAsyncWebServer is also fro esp8266 and esp32 .

**Comment by hoeken** [comment]
I don't have any immediate plans to do that, but I am also not opposed to
it.  If someone ports it, I would happily accept the PR.

The first step would be to see if ESP-IDF HTTP server is supported by
esp8266 as PsychicHttp is based on this.
