### ISSUE TITLE
Different Version Arduino And Github

### ISSUE THREAD

**Issue by hasankorkmazdev** [hoeken/PsychicHttp#70]
The version in the Arduino library manager seems very incomplete. Please make a new update.The version in the Arduino library manager seems very incomplete. Please make a new update.
![image](https://github.com/hoeken/PsychicHttp/assets/48335307/2c3217b5-841a-44dd-92e9-66eb18152201)

**Comment by theelims** [comment]
The easiest way is to download the zip file from github (Green CODE button) --> Download ZIP and import that into Arduino IDE. With the next official release the Arduino library will update itself.

Personal recommendation: switch to VSCode and Platformio.io

**Comment by hasankorkmazdev** [comment]
Thanks for advice I try arduino after i research platform.io :)
