### ISSUE TITLE
Ethernet compatibility 

### ISSUE THREAD

**Issue by acztassi** [hoeken/PsychicHttp#71]
Hello!
I would like to know if is your library compatible with LAN8720, or other Ethernet controllers?

**Comment by johnnytolengo** [comment]
The library is listening the port you want, so any lpwip interface is compatible.

**Comment by acztassi** [comment]
Thanks!!! 
I have only other question!! As it’s forbidden to use Delay and yield, may I use the mutex to interact with variables from other threads? Because causas a little delay in the callbacks

**Comment by johnnytolengo** [comment]
if the delay is too long that may block the main process causing a reboot. For that cases a good option is to use a queue, look a FreeRtos documentation.

**Comment by acztassi** [comment]
Thanks for the explanation
