### ISSUE TITLE
Support HTTP_ANY

### ISSUE THREAD

**Issue by dzungpv** [hoeken/PsychicHttp#79]
I see HTTP_ANY support in the ESP IDF, so if I am using there new component, the HTTP_ANY support out of the box or must change in the code? 
I am using PsychicHttp in ESP IDF with Arduino as component and can run alpha Arduino Core 3.0 so it not a problem with running latest SDKs.

Edit: PR support HTTP_ANY: https://github.com/espressif/esp-idf/commit/1d81af367d9d44f3bddf8ee3c0f9c53315fe976c

**Comment by hoeken** [comment]
Looks like this won't be supported until ESP-IDF 5.4.  In the meantime, check out our v2-dev branch.  It now supports HTTP_ANY.
