### ISSUE TITLE
ElegantOTA support

### ISSUE THREAD

**Issue by TinyAxolotl** [hoeken/PsychicHttp#86]
Hello, does anybody tried to port ElegantOTA to the PsyhicHTTP? Any forks?
Maybe someone created OTA based on Psyhic HTTP?

**Comment by T94T** [comment]
See https://github.com/ayushsharma82/ElegantOTA/issues/156

You need to use [HowardsPlayPen/ElegantOTA](https://github.com/HowardsPlayPen/ElegantOTA) for it to work for now.

**Comment by hoeken** [comment]
This is awesome.  We are working on a v2.0 that will be more compatible with Psychic so hopefully it will work out of the box soon.
