### ISSUE TITLE
"No Server certificate supplied"

### ISSUE THREAD

**Issue by gradhocJcalvo** [hoeken/PsychicHttp#93]
Conditions: With new update from espressif on Arduino IDE enviroment, (3.0 board version). And using ESP32-S3. Default partition scheme. SSL hast to be enabled on example. With http it works fine.

BUG: E (1160) esp_https_server: No Server certificate supplied

-With example of the library.

-LittleFS  uploaded (no errors when reading it).

If I downgrade to V2.16 of board all works fine.

Thank you very much.

**Comment by connornishijima** [comment]
I have this issue as well, documented in my own repo's issue here:

https://github.com/Lixie-Labs/Emotiscope/issues/86

(I'm also on espressif/arduino-esp32 3.0.0 / IDF 5.x)

**Comment by mhaberler** [comment]
I have the same issue, see https://github.com/hoeken/PsychicHttp/issues/103

**Comment by mhaberler** [comment]
https://github.com/hoeken/PsychicHttp/pull/104 should fix this problem

**Comment by mhaberler** [comment]
@connornishijima @gradhocJcalvo

a fix has been merged, could you verify this works for you?

**Comment by hoeken** [comment]
fixed
